## CUSTOM _pages DIRECTORY
include: [_pages]

## CORE ATTRIBUTES
url: "http://gmelgaba.github.io/"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Gonzalo Melgar"
job: "Software Engineer"

## SECTIONS ENABLED
sections:
- about: true
- companies: true
- fun_facts: true

## NAVIGATION REDIRECTS
navigation:
- text: about
  url: /
  icon: ion-person
  layout: page
- text: resume
  url: /experience/
  icon: ion-android-list
  layout: page
- text: tools
  url: /tools/
  icon: ion-hammer
  layout: page
# - text: blog
#   url: /blog/
#   icon: ion-chatbox-working
#   layout: post
- text: playlists
  url: /playlists/
  icon: ion-headphone
  layout: page

## [Profile Card] SOCIAL URLs
socials:
- url: https://stackoverflow.com/users/12064160/gonzalo?tab=profile
  icon: fa-stack-overflow
- url: https://www.linkedin.com/in/gmelgaba/
  icon: fa-linkedin
- url: https://github.com/gmelgaba
  icon: fa-github
- url: https://open.spotify.com/user/0ny35jaa9ga0azi1smsg5h15s?si=WI9AQHRfS0usJCWcv1bENQ
  icon: fa-spotify
- url: https://www.youtube.com/channel/UChHDiwGkIg1_FKFR0VMIu7A
  icon: fa-youtube

## [About] FUN FACTS
fun_facts:
- text: "Music enthusiast"
  icon: fa-music
- text: "Videogame addict"
  icon: fa-gamepad
- text: "Trashball pro player"
  icon: fa-trash
- text: "Amazon shopaholic"
  icon: fa-credit-card

## [Resume] EXPERIENCE
resume:
  experience:
  - company: "tarmac"
    imagePath: "/assets/images/experience/tarmac.jpg"
    url: https://tarmac.io/
    duration: "8 years"
    roles:
      - position: "Team Leader"
        type: "Fulltime"
        period: "sept 2020 - current"
        duration: ""
        description: |
          Leading multiple teams of developers across different products trying to create an open communication culture.

          Some of the responsibilities I had were
          <ul>
            <li>Set clear team goals</li>
            <li>Client communication</li>
            <li>Oversee day-to-day operation</li>
            <li>Facilitating team needs in order to get alligned with the current objective</li>
            <li>Annual review and monthly performance meetings with all team members</li>
            <li>Running interviews with potential company candidates</li>
          </ul>

      - position: "Principal Engineer"
        type: "Fulltime"
        period: "jun 2018 - sept 2020"
        duration: "2 years and 4 months"
        description: |
          The role involved being an official reference of a specific technology, Node.js in my case.
          Some of the responsibilities I had were
          <ul>
            <li>Code audits</li>
            <li>Hiring Interviews</li>
            <li>Candidates assessment</li>
            <li>Onboarding meetings with new recruits</li>
            <li>Occasional Sales appearances</li>
            <li>Internal reviews</li>
          </ul>

      - position: "Senior Software Developer"
        type: "Fulltime"
        period: "jan 2016 – jun 2018"
        duration: "2 years and 6 months"
        description: |
          Worked across different clients and was lucky enough to play with different technologies in the meantime, such as:
          <ul class="left-list">
            <li>express.js</li>
            <li>typescript</li>
            <li>node.js</li>
            <li>aws (s3, lambda, cloudwatch, glue)</li>
          </ul>
          <ul class="right-list">
            <li>angular 7+</li>
            <li>Ruby</li>
            <li>insomnia</li>
          </ul>

      - position: "Semi Senior Software Developer"
        type: "Part-time"
        period: "jun 2014 – dec 2015"
        duration: "1 year and 7 months"
        description: |
          Worked across different clients and was lucky enough to play with different technologies in the meantime, such as:
          <ul class="left-list">
            <li>node.js</li>
            <li>angular 1.x</li>
            <li>gulpjs</li>
            <li>aws (ec2, elasticbeanstalk, s3, lambda)</li>
          </ul>
          <ul class="right-list">
            <li>Ruby on Rails</li>
            <li>Ionic</li>
            <li>Laravel</li>
            <li>RiotJS, CucumberJS</li>
          </ul>

  - company: "spiria srl"
    imagePath: "/assets/images/experience/spiria.jpg"
    url: http://www.spiria.com.uy/
    duration: "2 years and 9 months"
    roles:
      - position: "Junior Software Developer"
        type: "Part-time"
        period: "oct 2011 - jun 2014"
        duration: "2 years and 9 months"
        description: |
          Collaborated in a team-focused environment providing creation, and support in different applications, mostly web and mobile hybrids. Some of the techs I used:<br>
          <ul class="left-list">
            <li>html, js, css</li>
            <li>php</li>
            <li>native android</li>
            <li>slim</li>
          </ul>
          <ul class="right-list">
            <li>native android</li>
            <li>phonegap</li>
            <li>titanium app celerator</li>
            <li>webapps</li>
          </ul>

  - company: "vtv Uruguay"
    imagePath: "/assets/images/experience/vtv.jpg"
    url: http://www.spiria.com.uy/
    duration: "1 year y 8 months"
    roles:
      - position: "Graphics Operator"
        type: "Fulltime"
        period: "mar 2010 - oct 2011"
        duration: "1 year and 8 months"
        description: |
          Responsible for producing suitable accurate graphic captions across a variety fo live productions and different national events.
          <ul>
            <li>Software: Photoshop CS10, CG5 multichannel.</li>
            <li>Daily Broadcasts: News Broadcast VTV Noticias Morning Edition, Dia a Dia, News Boardcast VTV Noticias Noon Edition, Sin limite.</li>
            <li>Weekly broadcasts/events: Rumbo a la Cancha, Mid-term elections, South American U-20 Championship, Uruguayan Championship, American Cup 2011, Basketball, among others.</li>
          </ul>

  ## EDUCATION
  education:
  - name: "Universidad de la República"
    imagePath: "/assets/images/education/fing.jpg"
    url: https://www.fing.edu.uy/
    period: "2007 – 2017"
    title: "Software Engineer"
    description: "The Computer Engineer career aims at a broad and coherent coverage in the planning, development, maintenance and application of computerized systems, which together with the acquired experience, will be projected in a competent professional."
  - name: "Instituto Tecnológico Superior"
    imagePath: "/assets/images/education/its.jpg"
    url: https://www.linkedin.com/school/arias-balparda/about/
    period: "2004 – 2006"
    title: "Computer Technician"
    description: "The superior technological institute of the CETP - UTU specialized mainly in Computer Science. In it, courses are taught ranging from EMT Technological Middle Education (Level II), Tertiary Technical Course in Networks and Software to the career of Computer Technologist, in agreement with the University of the Republic."

## [Playlists]
playlists:
  - url: "https://open.spotify.com/playlist/1PMb1FaLWJdLPKV0tz7F85?si=37eb3cd48f904978"
    imagePath: "/assets/images/playlists/perversions.jpg"
    title: "perVersions"
    description: "best rock/metal covers"
  - url: "https://open.spotify.com/user/0ny35jaa9ga0azi1smsg5h15s/playlist/0b44wqCVZbmrTP5HNwt5Pm?si=8ca45a4aae234805"
    imagePath: "/assets/images/playlists/anime.jpg"
    title: "anime"
    description: "anime opening/ending songs"
  - url: "https://open.spotify.com/playlist/2PFryBXfj6ZqJeXwVGnnJO?si=a74abc4f16224787"
    imagePath: "/assets/images/playlists/rocketman.jpg"
    title: "rocketman"
    description: "Elton John's rocketman movie ost originals"
  - url: "https://open.spotify.com/playlist/4Y8FZQA3yqZaXhAE44FfJw?si=b713e46a91894aa9"
    imagePath: "/assets/images/playlists/roadtrip.jpg"
    title: "roadtrip"
    description: "songs to listen while taking a roadtrip"
  - url: "https://open.spotify.com/playlist/7pNGWvGYEZB47iNsMF0G86?si=b9030434e65645d7"
    imagePath: "/assets/images/playlists/last-of-us.jpg"
    title: "last of us"
    description: "last of us OST songs mostly acoustic"
  - url: "https://open.spotify.com/playlist/2jnf3EgFNH2hX6L2ekTxGH"
    imagePath: "/assets/images/playlists/crying-eyes.jpg"
    title: "crying eyes"
    description: "ballads"
  # - url: "https://open.spotify.com/playlist/2GsgarPY9pxzH5QFOBjWs1"
  #   imagePath: "/assets/images/playlists/calvo.jpg"
  #   title: "musica para que el calvo intolerante compañero de oficina se indigne, Vol I"
  #   description: "Bosio's favorite 90s pop songs. The legend says that after the revolution, he used to listen to this playlist each sunset dreaming about world peace."


## [Tools] DEV TOOLS
tools:
  - url: "https://code.visualstudio.com/"
    imagePath: "/assets/images/tools/vscode.png"
    title: "VS Code"
    description: "I've been jumping a lot between editors and for me, VS Code is the best choise out there. It's a great editor with a great community and tons of usefull extensions to add."
  - url: "https://www.warp.dev/"
    imagePath: "/assets/images/tools/warp.png"
    title: "warp"
    description: "This is by far the best terminal option out there. Warp is a fully native, GPU-accelerated, Rust-based terminal, it's currently in beta and onnly has support for Mac, but you should try it if able."
  - url: "https://www.gitkraken.com/"
    imagePath: "/assets/images/tools/gitkraken.png"
    title: "GitKraken"
    description: "Powerful graphical interface for Git as an alternative to the command line. If you're tired of typing the same commands over and over, this is the best option to take."
  - url: "https://dbeaver.io/"
    imagePath: "/assets/images/tools/dbeaver.png"
    title: "DBeaver"
    description: "Free, open source, graphical database management tool for database. Easy to use and super helpful in times of need."
  - url: "https://insomnia.rest/"
    imagePath: "/assets/images/tools/insomnia.png"
    title: "Insomnia"
    description: "Free Cross-Platform Desktop Framework for building and using APIs. For graphql APIs in particular this one takes the first place."

