## CUSTOM _pages DIRECTORY
include: [_pages]

## CORE ATTRIBUTES
url: "http://gmelgaba.github.io/"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Gonzalo Melgar"
job: "Software Engineer"

## SECTIONS ENABLED
sections:
- about: true
- companies: false
- fun_facts: true

## [Profile Card] SOCIAL URLs
socials:
- url: https://stackoverflow.com/users/12064160/gonzalo?tab=profile
  icon: fa-stack-overflow
- url: https://www.linkedin.com/in/gmelgaba/
  icon: fa-linkedin
- url: https://github.com/gmelgaba
  icon: fa-github
- url: https://open.spotify.com/user/0ny35jaa9ga0azi1smsg5h15s?si=WI9AQHRfS0usJCWcv1bENQ
  icon: fa-spotify
- url: https://www.youtube.com/channel/UChHDiwGkIg1_FKFR0VMIu7A
  icon: fa-youtube

## [About] NAVIGATION REDIRECTS
navigation:
- text: about
  url: /
  icon: ion-person
  layout: page
- text: resume
  url: /resume/
  icon: ion-android-list
  layout: page
- text: playlists
  url: /playlists/
  icon: ion-headphone
  layout: page
- text: blog
  url: /blog/
  icon: ion-chatbox-working
  layout: post
- text: contact
  url: /contact/
  icon: ion-at
  layout: page

playlists:
  - url: "https://open.spotify.com/playlist/1PMb1FaLWJdLPKV0tz7F85?si=37eb3cd48f904978"
    title: "perVersions"
    description: "best rock/metal covers"
  - url: "https://open.spotify.com/playlist/2jnf3EgFNH2hX6L2ekTxGH"
    title: "crying eyes"
    description: "ballads"
  - url: "https://open.spotify.com/playlist/2GsgarPY9pxzH5QFOBjWs1"
    title: "musica para que el calvo intolerante compañero de oficina se indigne, Vol I"
    description: "Bosio's favorite 90s pop songs. The legend says that after the revolution, he used to listen to this playlist each sunset dreaming about world peace."

## [About] FUN FACTS
fun_facts:
- text: "Music enthusiast"
  icon: fa-music
- text: "Videogame addict"
  icon: fa-gamepad
- text: "1.000 cups of coffee"
  icon: fa-coffee
- text: "10 Countries visited"
  icon: fa-flag


## EXPERIENCE
resume:
  experience:
  - company: "tarmac"
    imagePath: "/assets/images/experience/tarmac.jpg"
    url: https://tarmac.io/
    duration: "7 years"
    roles:
      - position: "Principal Engineer"
        period: "jun 2018 - current"
        duration: ""
        description: "
          Node.js
          - Code audits
          - Hiring Interviews
          - Candidates assessment
          - Onboarding interviews
          - Internal reviews
        "
      - position: "Senior Software Developer"
        period: "jan 2016 – jun 2018"
        duration: "2 years and 6 months"
        description: "
          - Node.js
          - express
          - jest
          - typescript
          - Angular 7
        "
      - position: "Semi Senior Software Developer"
        period: "jun 2014 – dec 2015"
        duration: "1 year and 7 months"
        description: "
          Node.js, Angular 2+, GulpJS, Amazon Web Services (EC2, ElasticBeanstalk, S3, Lambdas), Travis CI, Materializecss, Postman, Ruby on Rails, Ionic, Laravel, RiotJS, CucumberJS
        "
  - company: "spiria srl"
    imagePath: "/assets/images/experience/spiria.jpg"
    url: http://www.spiria.com.uy/
    duration: "2 years and 9 months"
    roles:
      - position: "Junior Software Developer"
        period: "oct 2011 - jun 2014"
        duration: "2 years and 9 months"
  - company: "VTV Uruguay"
    imagePath: "/assets/images/experience/vtv.jpg"
    url: http://www.spiria.com.uy/
    duration: "1 year y 8 months"
    roles:
      - position: "Junior Software Developer"
        period: "mar 2010 - oct 2011"
        period: "mar 2010 - oct 2011"
        duration: "1 year y 8 months"

  ## EDUCATION
  education:
  - name: "Universidad de la República"
    imagePath: "education/fing.jpg"
    url: https://www.fing.edu.uy/
    period: "2007 – 2017"
  - name: "Instituto Tecnológico Superior"
    imagePath: "education/its.jpg"
    url: https://www.linkedin.com/school/arias-balparda/about/
    period: "2004 – 2006"